### PR TITLE
Enhancement: Use displayName for better to investigate on prod

### PR DESCRIPTION
**Pull request by fResult**
- [x] Use the proper components' type
- [x] Assign `displayName` for better investigating with ReactDevtools on the prod. (without `displayName`, it will don't know the component's name  in the dev tools)   
  image

### CODE REVIEW

**Comment by dtinth** [comment]
@fResult I’m not sure about the `displayName` thing. When developing do you use `pnpm run dev`? If the component names show up when using `pnpm run dev` then no need to add `displayName`.

**Comment by dtinth** [comment]
Ohh, I just saw the title — on production. I don’t think it is necessary because it adds a maintenance burden.

On the component type, the convention for this project is this:

```ts
interface MyComponent {}
function MyComponent(props: MyComponent) {
  return <></>
}
```

So, no need to change to `FC`. That’s an extra import.

**Comment by fResult** [comment]
Okay, I see. Thanks for sharing krub.

**Comment by dtinth** [comment]
Sure, let’s close this for now. Cheers!

**Pull request closed without merging**
